[mongodb]
mongodb-dev.techdaws.online

[catalogue]
catalogue-dev.techdaws.online

[redis]
redis-dev.techdaws.online

[user]
user-dev.techdaws.online

[cart]
cart-dev.techdaws.online

[all:vars]
ansible_user=ec2-user
ansible_password= DevOps321
MONGODB_HOST=mongodb-dev.techdaws.online