- name: Setup MongoDB Server
  hosts: mongodb
  become: yes

  tasks:

    - name: Copy MongoDB repo file
      copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: installed

    - name: Enable MongoDB visibility
      replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start MongoDB
      systemd:
        name: mongod
        state: started
        enabled: yes

    - name: Remove old schema directory if exists
      file:
        path: /tmp/mongodb-main
        state: absent

    - name: Download MongoDB schema
      git:
        repo: https://github.com/roboshop-devops-project/mongodb.git
        dest: /tmp/mongodb-main

    - name: Drop catalogue database
      shell: mongosh --quiet --eval "db.getSiblingDB('catalogue').dropDatabase()"

    - name: Drop users database
      shell: mongosh --quiet --eval "db.getSiblingDB('users').dropDatabase()"

    - name: Load catalogue schema
      shell: mongosh < /tmp/mongodb-main/catalogue.js

    - name: Load users schema
      shell: mongosh < /tmp/mongodb-main/users.js