- name: Setup MongoDB
  hosts: mongodb
  become: yes
  tasks:

    - name: Copy MongoDB repo
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/mongo.repo
        content: |
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
          enabled=1
          gpgcheck=0

    - name: Install MongoDB
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: Start MongoDB
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

    - name: Allow remote connections
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0

    - name: Restart MongoDB
      ansible.builtin.service:
        name: mongod
        state: restarted