- name: configure mongodb server
  hosts: mongodb
  become: yes

  tasks:
    - name: copy mongodb repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: enable and start mongodb
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

    - name: allow remote connections
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0

    - name: restart mongodb
      ansible.builtin.service:
        name: mongod
        state: restarted

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download mongodb schema
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/mongodb-v3.zip
        dest: /tmp/mongodb.zip

    - name: extract schema
      ansible.builtin.unarchive:
        src: /tmp/mongodb.zip
        dest: /app
        remote_src: yes

    - name: load catalogue schema
      ansible.builtin.command: mongosh < /app/mongodb/catalogue.js

    - name: load users schema
      ansible.builtin.command: mongosh < /app/mongodb/users.js