# ansible-playbook -i locolhost, -e 'instances=["mongodb", "catalogue", "redis", "user", "cart", "mysql", "shipping", "rabbitmq", "payment", "frontend"]' roboshop.yaml

- name: create ec2 and r53 records
  hosts: all
  connection: local

  vars:
    sg_id: sg-095a16b494e83f916
    ami_id: ami-0220d79f3f480ecf5
    domain_name: techdaws.online
    env: dev
    action: create
    instances:
      - mongodb
      - catalogue

  tasks:

    - name: create ec2 instance
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        name: "{{ item }}-{{ env }}"
        tags:
          Project: roboshop
          Component: "{{ item }}"
          environment: "{{ env }}"
          name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_instance
      when: action == "create"

    - name: create r53 records
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
      loop: "{{ ec2_instance.results }}"
      when: action == "create"

    - name: create frontend dns
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "roboshop-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
      loop: "{{ ec2_instance.results }}"
      when:
        - item.item == "frontend"
        - action == "create"

    - name: delete ec2 instance
      amazon.aws.ec2_instance:
        state: absent
        name: "{{ item }}-{{ env }}"
        wait: false
      loop: "{{ instances }}"
      when: action == "delete"

    - name: delete r53 records
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "{{ item }}-{{ env }}.{{ domain_name }}"
        type: A
      loop: "{{ instances }}"
      when: action == "delete"